name: Deploy Frontend Angular

on:
  push:
    branches:
      - main

jobs:
  deploy-todo-em-um:
    runs-on: self-hosted
    
    steps:
      - name: 1. Baixar Código do GitHub
        uses: actions/checkout@v4

      - name: 2. Instalar Dependências e Compilar Angular
        run: |
          npm install
          ng build --configuration=production

      - name: 3. Identificar e Mover Ficheiros para o Servidor
        run: |
          echo "--- Pastas reais geradas dentro de dist: ---"
          ls -la dist/
          
          # Limpa a pasta do servidor
          sudo rm -rf /home/dailes/meu-servidor/angular-dist/*
          
          # Copia o conteúdo de qualquer subpasta que o Angular tenha criado para a raiz do servidor
          sudo cp -r dist/*/* /home/dailes/meu-servidor/angular-dist/ 2>/dev/null || sudo cp -r dist/* /home/dailes/meu-servidor/angular-dist/

      - name: 4. Reiniciar Nginx
        run: |
          cd /home/dailes/meu-servidor
          docker compose up -d --force-recreate frontend-nginx
