name: Deploy Frontend Angular

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, frontend] # Alvo: Seu runner do front no WSL
    
    steps:
      - name: Baixar Código do GitHub
        uses: actions/checkout@v4

      - name: Instalar Dependências e Compilar Angular
        run: |
          npm install
          ng build --configuration=production

      - name: Mover Build para a pasta do Servidor
        run: |
          # 1. Mostra no log do GitHub o nome real da pasta gerada pelo Angular
          echo "--- Pastas geradas dentro de dist: ---"
          ls -la dist/
          
          # 2. Executa a limpeza e a cópia (usando uma máscara genérica para copiar qualquer pasta que esteja lá dentro)
          sudo rm -rf /home/dailes/meu-servidor/angular-dist/*
          sudo cp -r dist/*/* /home/dailes/meu-servidor/angular-dist/ 2>/dev/null || sudo cp -r dist/* /home/dailes/meu-servidor/angular-dist/

      - name: Reiniciar Nginx
        run: |
          cd /home/dailes/meu-servidor
          docker compose up -d --force-recreate frontend-nginx
